### PR TITLE
add maltese and nepali

### PR DESCRIPTION
**Pull request by joshreisner**
Screenshot 2024-08-18 at 10 56 36 AM

per https://github.com/code4recovery/online-meeting-list/issues/59#issuecomment-2295323887

### CODE REVIEW

**Comment by mattbylett** [comment]
Hey Josh - Been a while - sorry Ive been AWOL - life happened!

Thanks for this - what you need from me?

**Comment by joshreisner** [comment]
thanks @mattbylett i wasn't sure if it was set to auto-deploy. looks like it did though! so just merge the other PR and test it by adding the type to some meetings - looks like this is one of the nepali meetings: https://central.aa-intergroup.org/meetings/66c1f556908825426f31ca64

**Comment by mattbylett** [comment]
Awesome sounds good thanks Josh - so Central seems to be all good...

Do I need to rebuild the meeting directory?

**Comment by joshreisner** [comment]
yes

**Comment by mattbylett** [comment]
Cool done that _ i'll push it shortly :)

**Comment by mattbylett** [comment]
Pushed new meeting guide :)

Thanks for your support Josh

We help businesses develop integrated ecommerce digital solutions

Matthew Bylett
Founder Think New Ltd
022 029 2881

**Pull request merged**
